### ISSUE TITLE
Shape mismatch in dataset.py

### ISSUE THREAD

**Issue by darioshehni** [BadourAlBahar/pose-with-style#10]
running train.py causes the following error

```
 File "/home/dario/pose-with-style/dataset.py", line 131, in __getitem__
    silhouette1 = 1-((1-silhouette1) * (input_densepose[:, :, 0] == 0).astype('float'))
ValueError: operands could not be broadcast together with shapes (512,348,3) (512,348)
```

The error appears to be fixed by changing line 131 to
`silhouette1 = 1-((1-silhouette1) * (input_densepose[:, :, :] == 0).astype('float'))`

**Comment by darioshehni** [comment]
the error is better fixed by unsqueezing:
` silhouette1 = 1-((1-silhouette1) * np.expand_dims((input_densepose[:, :, 0] == 0).astype('float'), axis=2))`

this introduces a new error however:
`  File "train.py", line 198, in train
    real_img = real_img * sil
RuntimeError: The size of tensor a (512) must match the size of tensor b (167) at non-singleton dimension 4`

**Comment by BadourAlBahar** [comment]
The silhouette is the foreground mask. It can be of shape HxW only no need for the 3 channels. Removing those would fix the issue. I think you are reading this mask as RGB.
Explanation of this line of code: Because the silhouette was not great, I just union it with densepose mask. The first channel of densepose is (i) which is the ID if the body parts. 0 is for background. This way I union the not so perfect foreground mask with the densepose foreground mask.

**Comment by darioshehni** [comment]
Thank you for your reply @BadourAlBahar 

Simply adding an additional dimension did the trick:
`silhouette1 = 1-((1-silhouette1) * np.expand_dims((input_densepose[:, :, 0] == 0).astype('float'), axis=2))`

This introduces a new error however in train.py line 198:

`File "train.py", line 198, in train real_img = real_img * sil RuntimeError: The size of tensor a (512) must match the size of tensor b (167) at non-singleton dimension 4`

Because sil now is of shape torch.Size([1, 1, 512, 348, 167]). Which doesn't look right to me.

**Comment by BadourAlBahar** [comment]
You should not add an additional dimension.

**Comment by BadourAlBahar** [comment]
You should not add more dimensions. Keep the [line](https://github.com/BadourAlBahar/pose-with-style/blob/main/dataset.py#L119) as is.
What you need to do is verify that your silhouette is in the shape HxW, and not HxWx3.

**Comment by darioshehni** [comment]
Right, PGN outputs segmentation masks with the name *_sil.png, so I used that.
But I should have been using the silhouette images. 

Thanks
