### ISSUE TITLE
Garment Transfer on lower body is missing bikini part 

### ISSUE THREAD

**Issue by kieutrongthien** [BadourAlBahar/pose-with-style#12]
The inferred result is missing the bikini part, how can this be improved? I think the problem is in UV space body part segmentation.

Here is my result:

![9c945c7f-ec1a-4fec-9bca-0028bf300ebc_iuv](https://user-images.githubusercontent.com/9605103/164680275-0f810c2f-2dd6-4283-98d6-46733b5874d7.png)
![9c945c7f-ec1a-4fec-9bca-0028bf300ebc](https://user-images.githubusercontent.com/9605103/164680280-d64d1e0a-eb6a-4336-8e8a-a0ba8b17a89a.png)
![9c945c7f-ec1a-4fec-9bca-0028bf300ebc_e630766a-d353-4d8c-a79f-e1cfeb430618](https://user-images.githubusercontent.com/9605103/164680287-60c60271-ed72-4717-82ad-17ff101311e3.png)

**Comment by BadourAlBahar** [comment]
Yes. You are correct. You should modify the body part segmentation until you get the desired effect.
