### ISSUE TITLE
Silhouettes generation issue

### ISSUE THREAD

**Issue by harryzhangOG** [BadourAlBahar/pose-with-style#14]
Hi, Thanks for making the code available. I have a question regarding the silhouettes generation. I followed your steps and managed to run PGN inference on the deep fashion dataset. However, it is very slow to generate the segmasks (~20s per image) and often runs with out-of-memory warnings.  For the reference, I am using nvidia V100 16Gb so it should be enough... Thus, would it be possible for you to share the segmasks to us via Google drive at your convenience? If not, would it be possible for you to share some pointers on how you made it run fast enough for all the 40k+ images? Thank you so much.

**Comment by darioshehni** [comment]
I had this same issue. You have to change the code so it actually uses the GPU. It's been a while so I'm not quite sure how I resolved it.

**Comment by harryzhangOG** [comment]
Hi @darioshehni. thanks for the reply, could you share some pointers on how u resolved it? thanks.

**Comment by darioshehni** [comment]
Confirm that the GPU is actually recognised and use `.to(device)` to push the network and all images to the GPU.

**Comment by BadourAlBahar** [comment]
Thank you very much for your interest. Here are the silhouettes for the [training set](https://filebox.ece.vt.edu/~Badour/pose-with-style/data/train_sil.zip) and [testing set](https://filebox.ece.vt.edu/~Badour/pose-with-style/data/test_sil.zip).
