### ISSUE TITLE
dp2coor.py is extremely slow

### ISSUE THREAD

**Issue by tuallen** [BadourAlBahar/pose-with-style#16]
Hello,

I'm running dp2coor.py on the DeepFashion high resolution test data as instructed in [Dataset and Downloads](https://github.com/BadourAlBahar/pose-with-style/blob/main/DATASET.md). However, it takes a long time (>20 seconds) to process each image. I believe it is because `scipy.interpolate.griddata` is slow on large matrices.

Is this expected behavior from dp2coor.py, and is there a way to speed it up? It would take an exorbitantly long time to process the training data at my current rate. Thank you.

**Comment by tasinislam21** [comment]
Have you found the solution?

**Comment by tuallen** [comment]
@1702609 I remember making two changes. First, [I implemented a faster `griddata`](https://stackoverflow.com/a/14072543), but I'm afraid you'll need to do that yourself as I cannot share my code either.

The second change also speeds up the code a lot; however, it might not be the best fit for your dataset. Change line 110 of `dpcoor.py` to the following:
```
            uv_coor, uv_mask, uv_symm_mask  = getSymXYcoordinates(iuv, resolution = 256)
```
My images were 256x174 and I didn't find any impact on the quality of the outputs.
