### ISSUE TITLE
GPU'S ARE REQUIRED?

### ISSUE THREAD

**Issue by lokesh0606** [BadourAlBahar/pose-with-style#2]
Is it necessary that we need gpu's to run or test this repo. I'm currently facing this issue and it's asking me to set the cuda home path and i have removed all .cuda() for the all the .py files
![Screenshot 2022-01-21 120429](https://user-images.githubusercontent.com/84309307/150478968-9257bf37-888c-4339-a260-f561cf2fb4fd.jpg)

**Comment by BadourAlBahar** [comment]
I have not tried running it without a GPU, but I would assume that a GPU is required. If you do not have access to a GPU, you can use Google Colab. Here is a [Colab notebook](https://colab.research.google.com/github/tg-bomze/collection-of-notebooks/blob/master/HomeStylist.ipynb) created by [@tg_bomze](https://twitter.com/tg_bomze).
