### ISSUE TITLE
Discriminator loss too low

### ISSUE THREAD

**Issue by tasinislam21** [BadourAlBahar/pose-with-style#23]
I am using this model to train on my dataset. After a few epochs, the loss value of the discriminator gets low as 0.001, and the generator would be around 5-11. Is this normal?

**Comment by BadourAlBahar** [comment]
Please note that when the discriminator loss goes to zero this means that the discriminator is perfect at telling real from fake images. 
Check the real/fake images.. can you easily tell which one is real and which one is fake?

An example of when I had this issue happen is when the real image had zero side padding to make it square. The generated fake image can never generate exact zeros, best case ~0.0001. Hence, the discriminator can use this to easily distinguish real from fake images. 
To fix this, I also added zero padding to the fake image such that at the sides of both images would have exact zeros.

**Comment by tasinislam21** [comment]
Thanks 

> Please note that when the discriminator loss goes to zero this means that the discriminator is perfect at telling real from fake images. Check the real/fake images.. can you easily tell which one is real and which one is fake?
> 
> An example of when I had this issue happen is when the real image had zero side padding to make it square. The generated fake image can never generate exact zeros, best case ~0.0001. Hence, the discriminator can use this to easily distinguish real from fake images. To fix this, I also added zero padding to the fake image such that at the sides of both images would have exact zeros.

Thanks for your response. There was a problem at my end. I did not remove the background of the real and fake images. Now I fixed that, and the error rate has been stabilised.
