### ISSUE TITLE
any guidance on creating silhouette ? 

### ISSUE THREAD

**Issue by johndpope** [BadourAlBahar/pose-with-style#3]
it's not spelled out how - and from image - seems like you're using some facebook pose? is it supposed to be black and white?

**Comment by BadourAlBahar** [comment]
If you look in [Dataset and Downloads](https://github.com/BadourAlBahar/pose-with-style/blob/main/DATASET.md), we show in step 3 what we used to compute the foreground mask. You can, however, use any method you wish.

**Comment by harryzhangOG** [comment]
Hi I am also having the same question. The PGN repo requires a very specific dataset structure that is not available in the deep fashion dataset. could you share how you bypass this? Thanks.
