### ISSUE TITLE
DensePose which version

### ISSUE THREAD

**Issue by GothParrot** [BadourAlBahar/pose-with-style#8]
Hi, thanks for this great project. Got it to work on your tests, going to run on my own images but got stuck looking for the right DensePose package and model. Can you share your densepose config, where you built from, and which model you used?

**Comment by GothParrot** [comment]
Oh nvm. Found your dataset instructions :)

**Comment by Yesmine006** [comment]
Hello @GothParrot I m trying to do the same on my own images so can you please help me with which instructions you followed

**Comment by GothParrot** [comment]
Hi @Yesmine006 it's been a while and I'm forgetting the details of running this project. But I found some old notes that might help you. These notes help you build a docker or python environment, and also help you run DensePose

# to run pose with style

conda install pytorch==1.8.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=11.2 -c pytorch

python inference.py --input_path ./data --input_name vi_resize --target_name fashionWOMENBlouses_Shirtsid0000635004_1front --CCM_pretrained_model models/CCM_epoch50.pt --pretrained_model models/posewithstyle.pt

python inference.py --input_path ./data --input_name fashionWOMENBlouses_Shirtsid0000635004_1front --target_folder ../girl_dance_poses --CCM_pretrained_model models/CCM_epoch50.pt --pretrained_model models/posewithstyle.pt

python3 inference.py --input_path ./data --CCM_pretrained_model models/CCM_epoch50.pt --pretrained_model models/posewithstyle.pt


# to run DensePose. Download NVIDIA docker, use GPU, about 7G

docker run --gpus all -d -it --rm nvcr.io/nvidia/pytorch:22.02-py3

docker run --gpus all -t -d nvcr.io/nvidia/pytorch:22.02-py3

docker exec -it vigilant_morse /bin/bash


pip install git+https://github.com/facebookresearch/detectron2@main#subdirectory=projects/DensePose

python apply_net.py show configs/densepose_rcnn_R_101_FPN_DL_s1x.yaml \
https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_101_FPN_DL_s1x/165712116/model_final_844d15.pkl \
pose_images dp_u -v

python apply_net.py dump configs/densepose_rcnn_R_101_FPN_DL_s1x.yaml \
https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_101_FPN_DL_s1x/165712116/model_final_844d15.pkl \
pose_images  --output girl_dance_iuv.pkl -v

docker cp vigilant_morse:/workspace/detectron2/projects/DensePose/girl_dance_iuv.pkl pose_images_iuv/

docker cp pose_images/* vigilant_morse:/workspace/detectron2/projects/DensePose/pose_images/

docker cp articulated-animation/data/vi.png vigilant_morse:/workspace/detectron2/projects/DensePose/

python pickle2png.py --pickle_file girl_dance_iuv.pkl --save_path iuv_img_outputs/

docker cp -a vigilant_morse:/workspace/detectron2/projects/DensePose/iuv_img_outputs/ ./
